
package com.viettel.vps.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "AuthorizedDataService", targetNamespace = "http://webservice.vps.viettel.com/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface AuthorizedDataService {


    /**
     * @param fullPath
     * @param path
     * @param dataId
     * @param domainType
     * @param dataName
     * @param dataCode
     * @param parentId
     * @param status
     * @return returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateDomainData", targetNamespace = "http://webservice.vps.viettel.com/", className = "com.viettel.vps.webservice.UpdateDomainData")
    @ResponseWrapper(localName = "updateDomainDataResponse", targetNamespace = "http://webservice.vps.viettel.com/", className = "com.viettel.vps.webservice.UpdateDomainDataResponse")
    @Action(input = "http://webservice.vps.viettel.com/AuthorizedDataService/updateDomainDataRequest", output = "http://webservice.vps.viettel.com/AuthorizedDataService/updateDomainDataResponse")
    public Boolean updateDomainData(
            @WebParam(name = "dataId", targetNamespace = "")
                    Long dataId,
            @WebParam(name = "parentId", targetNamespace = "")
                    Long parentId,
            @WebParam(name = "dataCode", targetNamespace = "")
                    String dataCode,
            @WebParam(name = "dataName", targetNamespace = "")
                    String dataName,
            @WebParam(name = "domainType", targetNamespace = "")
                    String domainType,
            @WebParam(name = "path", targetNamespace = "")
                    String path,
            @WebParam(name = "fullPath", targetNamespace = "")
                    String fullPath,
            @WebParam(name = "status", targetNamespace = "")
                    Long status);

    /**
     * @param actor
     * @param staffCode
     * @param description
     * @return returns com.viettel.vps.webservice.LockUserResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lockUserByStaffCode", targetNamespace = "http://webservice.vps.viettel.com/", className = "com.viettel.vps.webservice.LockUserByStaffCode")
    @ResponseWrapper(localName = "lockUserByStaffCodeResponse", targetNamespace = "http://webservice.vps.viettel.com/", className = "com.viettel.vps.webservice.LockUserByStaffCodeResponse")
    @Action(input = "http://webservice.vps.viettel.com/AuthorizedDataService/lockUserByStaffCodeRequest", output = "http://webservice.vps.viettel.com/AuthorizedDataService/lockUserByStaffCodeResponse")
    public LockUserResult lockUserByStaffCode(
            @WebParam(name = "actor", targetNamespace = "")
                    VpsActor actor,
            @WebParam(name = "staffCode", targetNamespace = "")
                    String staffCode,
            @WebParam(name = "description", targetNamespace = "")
                    String description);

    /**
     * @param password
     * @param loginName
     * @param appCode
     * @return returns com.viettel.vps.webservice.AuthorizedData
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAuthorizedData", targetNamespace = "http://webservice.vps.viettel.com/", className = "com.viettel.vps.webservice.GetAuthorizedData")
    @ResponseWrapper(localName = "getAuthorizedDataResponse", targetNamespace = "http://webservice.vps.viettel.com/", className = "com.viettel.vps.webservice.GetAuthorizedDataResponse")
    @Action(input = "http://webservice.vps.viettel.com/AuthorizedDataService/getAuthorizedDataRequest", output = "http://webservice.vps.viettel.com/AuthorizedDataService/getAuthorizedDataResponse")
    public AuthorizedData getAuthorizedData(
            @WebParam(name = "loginName", targetNamespace = "")
                    String loginName,
            @WebParam(name = "appCode", targetNamespace = "")
                    String appCode,
            @WebParam(name = "password", targetNamespace = "")
                    String password);

}
