
package com.viettel.vps.webservice;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "AuthorizedDataService", targetNamespace = "http://webservice.vps.viettel.com/", wsdlLocation = "http://10.58.71.134:8202/vps/AuthorizedDataService?wsdl")
public class AuthorizedDataService_Service
        extends Service {

    private final static URL AUTHORIZEDDATASERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTHORIZEDDATASERVICE_EXCEPTION;
    private final static QName AUTHORIZEDDATASERVICE_QNAME = new QName("http://webservice.vps.viettel.com/", "AuthorizedDataService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.58.71.134:8202/vps/AuthorizedDataService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTHORIZEDDATASERVICE_WSDL_LOCATION = url;
        AUTHORIZEDDATASERVICE_EXCEPTION = e;
    }

    public AuthorizedDataService_Service() {
        super(__getWsdlLocation(), AUTHORIZEDDATASERVICE_QNAME);
    }

    public AuthorizedDataService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTHORIZEDDATASERVICE_QNAME, features);
    }

    public AuthorizedDataService_Service(URL wsdlLocation) {
        super(wsdlLocation, AUTHORIZEDDATASERVICE_QNAME);
    }

    public AuthorizedDataService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTHORIZEDDATASERVICE_QNAME, features);
    }

    public AuthorizedDataService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthorizedDataService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns AuthorizedDataService
     */
    @WebEndpoint(name = "AuthorizedDataServicePort")
    public AuthorizedDataService getAuthorizedDataServicePort() {
        return super.getPort(new QName("http://webservice.vps.viettel.com/", "AuthorizedDataServicePort"), AuthorizedDataService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns AuthorizedDataService
     */
    @WebEndpoint(name = "AuthorizedDataServicePort")
    public AuthorizedDataService getAuthorizedDataServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.vps.viettel.com/", "AuthorizedDataServicePort"), AuthorizedDataService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTHORIZEDDATASERVICE_EXCEPTION != null) {
            throw AUTHORIZEDDATASERVICE_EXCEPTION;
        }
        return AUTHORIZEDDATASERVICE_WSDL_LOCATION;
    }

}
